// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkEiwsdN5-ksp7YdF7UNzXGvZDngIaNbo',
    appId: '1:389288958354:android:179cd032bb3bd4be66494b',
    messagingSenderId: '389288958354',
    projectId: 'appslg',
    storageBucket: 'appslg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmPGQDVJWtOajLMIJCeKNh2kMu0DXetQE',
    appId: '1:389288958354:ios:e7e8361f8f6d94e266494b',
    messagingSenderId: '389288958354',
    projectId: 'appslg',
    storageBucket: 'appslg.firebasestorage.app',
    androidClientId: '389288958354-3kc7da2vcgs5rv9vr8gq50ip01te417t.apps.googleusercontent.com',
    iosClientId: '389288958354-37fjk7n1ucb2dtk4qmpd29c2lhusgrds.apps.googleusercontent.com',
    iosBundleId: 'com.example.appslg',
  );

}